// Export Salesforce field metadata for Volunteer__c
module.exports = [
  { fullName: 'First_Name__c', label: 'First Name', type: 'Text', length: 80, required: true },
  { fullName: 'Last_Name__c', label: 'Last Name', type: 'Text', length: 80, required: true },
  { fullName: 'Email__c', label: 'Email', type: 'Email' },
  { fullName: 'Phone__c', label: 'Phone', type: 'Phone' },
  { fullName: 'Date_of_Birth__c', label: 'Date of Birth', type: 'Date' },
  { fullName: 'Volunteer_Type__c', label: 'Volunteer Type', type: 'Picklist', valueSet: { valueSetDefinition: { value: [ { fullName: 'Individual' }, { fullName: 'Company Representative' }, { fullName: 'Administrator' } ] } } },
  { fullName: 'Company_Name__c', label: 'Company Name', type: 'Text', length: 255 },
  { fullName: 'Profile_Picture_URL__c', label: 'Profile Picture URL', type: 'Text', length: 255 },
  { fullName: 'Facebook_Handle__c', label: 'Facebook Handle', type: 'Text', length: 100 },
  { fullName: 'Instagram_Handle__c', label: 'Instagram Handle', type: 'Text', length: 100 },
  { fullName: 'Text_Opt_In__c', label: 'Text Opt In', type: 'Checkbox', defaultValue: 'false' },
  { fullName: 'T_Shirt_Size__c', label: 'T Shirt Size', type: 'Picklist', valueSet: { valueSetDefinition: { value: [ { fullName: 'XXS' },{ fullName: 'XS' },{ fullName: 'S' },{ fullName: 'M' },{ fullName: 'L' },{ fullName: 'XL' },{ fullName: '2XL' },{ fullName: '3XL' },{ fullName: '4XL' },{ fullName: '5XL' } ] } } },
  { fullName: 'Why_Volunteer__c', label: 'Why Volunteer', type: 'LongTextArea', length: 32768, visibleLines: 3 },
  { fullName: 'Events_Signed_Up__c', label: 'Events Signed Up', type: 'LongTextArea', length: 32768, visibleLines: 3 },
  { fullName: 'Total_Hours_Available__c', label: 'Total Hours Available', type: 'Text', length: 100 },
  { fullName: 'Community_Service_Hours__c', label: 'Community Service Hours', type: 'Picklist', valueSet: { valueSetDefinition: { value: [ { fullName: 'Yes' }, { fullName: 'No' } ] } } },
  { fullName: 'Volunteer_Assignments__c', label: 'Volunteer Assignments', type: 'Text', length: 255 },
  { fullName: 'Other_Assignment__c', label: 'Other Assignment', type: 'Text', length: 255 },
  { fullName: 'Tasks_to_Avoid__c', label: 'Tasks to Avoid', type: 'LongTextArea', length: 32768, visibleLines: 3 },
  { fullName: 'Skills_to_Use__c', label: 'Skills to Use', type: 'LongTextArea', length: 32768, visibleLines: 3 },
  { fullName: 'Certifications__c', label: 'Certifications', type: 'LongTextArea', length: 32768, visibleLines: 3 },
  { fullName: 'Certification_File_URL__c', label: 'Certification File URL', type: 'Text', length: 255 },
  { fullName: 'Time_Preference__c', label: 'Time Preference', type: 'Text', length: 255 },
  { fullName: 'Day_Preference__c', label: 'Day Preference', type: 'Text', length: 255 },
  { fullName: 'Location_Preference__c', label: 'Location Preference', type: 'Picklist', valueSet: { valueSetDefinition: { value: [ { fullName: 'Indoor' }, { fullName: 'Outdoor' }, { fullName: 'No preference' } ] } } },
  { fullName: 'Comfortable_With__c', label: 'Comfortable With', type: 'Text', length: 255 },
  { fullName: 'Accommodations_Needed__c', label: 'Accommodations Needed', type: 'LongTextArea', length: 32768, visibleLines: 3 },
  { fullName: 'Offender_Policy_Confirmed__c', label: 'Offender Policy Confirmed', type: 'Checkbox', defaultValue: 'false' },
  { fullName: 'Additional_Comments__c', label: 'Additional Comments', type: 'LongTextArea', length: 32768, visibleLines: 3 },
  { fullName: 'Electronic_Signature__c', label: 'Electronic Signature', type: 'Text', length: 255, required: true },
  { fullName: 'Signature_Date__c', label: 'Signature Date', type: 'Date', required: true },
  { fullName: 'Registration_Date__c', label: 'Registration Date', type: 'DateTime', required: true },
  { fullName: 'Status__c', label: 'Status', type: 'Picklist', valueSet: { valueSetDefinition: { value: [ { fullName: 'Active' }, { fullName: 'Inactive' }, { fullName: 'Suspended' } ] } } },
  { fullName: 'Total_Hours_Worked__c', label: 'Total Hours Worked', type: 'Number', precision: 18, scale: 2 },
  { fullName: 'Pass_Hash__c', label: 'Pass Hash', type: 'Text', length: 255 }
];
